### ISSUE TITLE
Error When running knex migrate:latest

### ISSUE THREAD

**Issue by nislo7** [samc621/SneakerBot#10]
**"knex migrate:latest"** gives:
_Error: knex: Required configuration option 'client' is missing._

**Comment by prossmeier** [comment]
Hello - 

I am not the dev. - but what is happening is that you have not exported a configuration file.

In the example - you will create a .env file called .env.local
then export that file `export NODE_ENV=local`

Then when you run `knex migrate:latest` - it will use the .env.local confg.

You can see here in my output the same thing happened.  Once I exported my .env.local - knex know to try to connect to PGSQL with the options in .env.local.

```
[root@shoebot SneakerBot]# knex migrate:latest
Error: knex: Required configuration option 'client' is missing.
    at new Client (/root/SneakerBot/node_modules/knex/lib/client.js:54:11)
    at Knex (/root/SneakerBot/node_modules/knex/lib/knex.js:14:28)
    at initKnex (/usr/lib/node_modules/knex/bin/cli.js:63:10)
    at async Command.<anonymous> (/usr/lib/node_modules/knex/bin/cli.js:231:26)
[root@shoebot SneakerBot]# export NODE_ENV=local
[root@shoebot SneakerBot]# knex migrate:latest
Using environment: local
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

Also of note - make sure you have a postgresql server up and running for this to work.

Paul

**Comment by samc621** [comment]
Hi @nislo7, yes @prossmeier is right - thanks for that! You need to make sure Postgresql is up and running, and that you configuration in `.env.local` is correct. If so, when you run `knex migrate:latest`, `knex` will know which DB to run the migrations on. I am closing this for now, but feel free to reopen if you're having further issues.
