### ISSUE TITLE
Error while running npx knex migrate:latest

### ISSUE THREAD

**Issue by Darxit** [samc621/SneakerBot#100]
tried running that after doing all other steps, got this error 

Not supported
Error: Not supported
    at importFile (/home/loon/SneakerBot/node_modules/knex/lib/migrations/util/import-file.js:10:29)

**Comment by Darxit** [comment]
issue 100 lets goooooo

**Comment by samc621** [comment]
What version of node are you using? What OS? Need more details to reproduce this error.

**Comment by Darxit** [comment]
{ npm: '6.14.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.1',
  http_parser: '2.9.3',
  icu: '66.1',
  modules: '64',
  napi: '5',
  nghttp2: '1.40.0',
  node: '10.19.0',
  openssl: '1.1.1d',
  tz: '2023c',
  unicode: '13.0',
  uv: '1.34.2',
  v8: '6.8.275.32-node.55',
  zlib: '1.2.11' }
there's all the node versions, 

running ubuntu 20.04.5 LTS

**Comment by samc621** [comment]
This is not going to work on Node 10. Can you please use the node version from the `.nvmrc` file? Should be Node 18.

Feel free to reopen if any issues persist.
