### ISSUE TITLE
Having an issue with knex config

### ISSUE THREAD

**Issue by imbruglia100** [samc621/SneakerBot#106]
I'm getting an error saying there is no client option when there is one. I haven't changed knexfile.js, and have followed the readme.md till the "npx knex migrate:latest" then I get the error

**Comment by samc621** [comment]
@imbruglia100 this error almost always happens when the `NODE_ENV` has not been set in your shell environment. Can you please confirm that it was set and that the value matches the name of your env file? E.g. if `NODE_ENV=local` then you should have populated an `.env.local` file.

**Comment by imbruglia100** [comment]
@samc621 Yes, so for whatever reason, it wasn't setting from Powershell. I just did it in cmd and it worked. Thank you

**Comment by samc621** [comment]
Thanks for the update! Closing this for now. Feel free to open a new Issue if anything else arises.
