### ISSUE TITLE
.env.local inputs

### ISSUE THREAD

**Issue by jerome102** [samc621/SneakerBot#13]
Hi there, I wanted to thank you for your project as I was making a nike bot with selerium and it would get flagged after about 10 mins of running so finding your bot really pleases me as it proves it is possible to make a good bot with enough time and effort :)
For these inputs below I understand the card and API key, but for email and DB would that be sites username and password login? 
Also DB/ email  ports and hosts? Got me a little lost
PORT=

DB_USERNAME=
DB_PASSWORD=
DB_NAME=
DB_PORT=
DB_HOST=

EMAIL_HOST=
EMAIL_PORT=
EMAIL_USERNAME=
EMAIL_PASSWORD=

CARD_NUMBER=
NAME_ON_CARD=
EXPIRATION_MONTH=
EXPIRATION_YEAR=
SECURITY_CODE=

API_KEY_2CAPTCHA=

PS..(I'm not that experienced with node.js and knex but am managing so far)
Thanks in advance

**Comment by samc621** [comment]
Hi @jerome102 thanks for mentioning that! I will say that there is a lot we can do to avoid antibot software, and the goal is always to look "as human as possible." This is why we run headful Chrome sessions, use natural delays between certain interactions, and more. We still encounter captchas sometimes, but we can handle them.

As for the env variables, the DB variables are based on your Postgres configuration. Running it locally, the default host is `localhost` or `127.0.01` and the default port is `5432`. The DB name, and the DB username/password are configured by you. Postgres provides instructions on how to set that stuff up on the link in the README. The email variables are for setting up an SMTP server for email notifications about things like manual captchas encountered, checkout success, checkout error, etc.

I am closing this issue for now, but feel free to open another one if anything else comes up.
