### ISSUE TITLE
Task setup

### ISSUE THREAD

**Issue by jerome102** [samc621/SneakerBot#14]
Hi there,
When setting up the tasks, the base URL refers to "https://nike.com" in my case I'm guessing,
otherwise I'm getting error with {baseUrl} syntax
```
Python 3 example POST {{baseUrl}}/v1/tasks
import requests
import json

url = "https://nike.com/v1/tasks"
#original: url = "{{baseUrl}}/v1/tasks"

payload = json.dumps({
  "site_id": 1,
  "url": "https://www.nike.com/t/lebron-18-basketball-shoe-M6DgN2/CQ9283-001",
  "style_index": 1,
  "size": "8.5",
  "shipping_speed_index": 0,
  "billing_address_id": 2,
  "shipping_address_id": 2,
  "notification_email_address": "jsmith@gmail.com"
})
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```
after running this I am getting the sites complete HTML  it looks like, quite different from the example response which was looking nice and neat aha
Is it running correctly? 
Also I wasn't running them in a specific location, shouldn't be in ..\SneakerBot-master\api\Tasks

**Comment by samc621** [comment]
Hi @jerome102, these requests are to be sent to the Node/Express API server you are running locally. So, if you are running the server on `PORT` 8000 on your local machine, the `baseUrl` would be `localhost:8000` or `127.0.0.1:8000`. The requests are not sent to Nike.com or any third party site. Please let me know if an
