### ISSUE TITLE
Command Issue

### ISSUE THREAD

**Issue by TheSwindler44** [samc621/SneakerBot#17]
Hi,
I'm attempting to run the following command as mentioned in the documentation:
`docker run -p 5900:5900 8000:8000 --env-file .env.docker sneakerbot`

However, I am receiving the following error: 
`Unable to find image '8000:8000' locally
docker: Error response from daemon: pull access denied for 8000, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

I'm just wondering if there was a possible mistype in the documentation or if my issue is more "extreme". Obviously I can remove one of the ports but then I feel I am missing something vital to the programs normal operations. Any help is appreciated!

**Comment by samc621** [comment]
Hi @TheSwindler44, thanks for opening this issue! It looks like there is indeed a typo in the documentation. We need the `-p` flag for each set of ports we want to expose when using `docker run`. I've updated that [here](https://github.com/samc621/SneakerBot/commit/d5fdea5247fc48bf303a9a87ac69a2f9aefe9556), and am closing this issue. Please feel free to open another issue if anything else comes up.

PS: make sure to run `docker build` in the root dir first, before trying the `docker run` command. And make sure that you have Postgres running and configured properly in your `.env.docker` file.
