### ISSUE TITLE
Is Address Line 2 supposed to be compulsory?

### ISSUE THREAD

**Issue by bryank91** [samc621/SneakerBot#19]
How to replicate:
![image](https://user-images.githubusercontent.com/2115372/116778479-bac89c80-aaa4-11eb-84cd-b32a843c6426.png)
Blank out address_line_2  and send a PATCH request to address/{id}

Suggestions:
Allow the user to not define anything as it is not required

**Comment by samc621** [comment]
Hi @bryank91 thanks for bringing this to my attention! I thought I had handled it a while back. Here is a [commit](https://github.com/samc621/SneakerBot/commit/8b517b4a81548c73d6093104fb2776602d9a5b4f) which will allow an empty string ('') for `address_line_2`. I am going to keep the `not-null` constraint on the field in Postgres.

I am closing this issue for now, please feel free to open a new one if any issues persist.
