### ISSUE TITLE
How to run this ?

### ISSUE THREAD

**Issue by pratikbendre** [samc621/SneakerBot#2]
hey, you can please explain how to run this with some documentation or explaination.

Thanks In Advance.

**Comment by samc621** [comment]
Hi @pratikbendre thanks for opening this issue, and sorry for the delay in getting back to you. I have been busy working on the Supreme integration following the relaunch of their site last week, and also making some fixes for the captcha solving on their site. 

Did you take a look at the documentation in the README? I've tried to lay out the step by step setup as best I possibly can there, but if you have any specific questions about it, I'm happy to try and further support you.
