### ISSUE TITLE
Windows issues?

### ISSUE THREAD

**Issue by carlInvoker666** [samc621/SneakerBot#24]
Sorry I am new here and I guess this is a noob question but, is there a problem running this code on windows platform?

and another noob question, hoping you will answer..

what IDE you used to build this project and yeah what's the OS needed? " Windows or MAC...
Thank you! much love with your work.

**Comment by samc621** [comment]
Hi @carlInvoker666, can you report any specific issues you're running on Windows? Perhaps a stack trace, steps to reproduce, etc. I will need more information to help you. I develop with VSCode on Mac OS but this should work across all platforms, especially with the Docker/Docker Compose version.

**Comment by 13ROY** [comment]
Hi @carlInvoker666 , I got this running locally on my windows laptop this week (not using docker), as @samc621 please provide more information, I will do my best to help.

**Comment by carlInvoker666** [comment]
I'm currently using my windows. and Im using VSCode. I am having a hard time reproducing the project. Can you help me out please? Thanks again, much love

**Comment by carlInvoker666** [comment]
A steps to reproduce would help me alot. Thanks again 😃

**Comment by 13ROY** [comment]
Hi @carlInvoker666 , as there are a few steps to get your local environment configured, have you read and followed the `README.md` at the root of the repo? If so, what output are you getting when you try to run the project?

**Comment by carlInvoker666** [comment]
Thanks @13ROY for the respond, I did read the README.md and I'm not  quite sure that I'm doing the right thing to execute the code.
I am having trouble with this step. " Configure environment variables " can you help me out on how I can do this? Thanks again, much love.

**Comment by 13ROY** [comment]
Hi @carlInvoker666 , have you tried to run the application yet? If so what is the output? 
In terms of the environment variables, I took a copy of the `.env.example` file, then called it `.env.local', I then set the NODE_ENV variable in the terminal (windows command) using `$ export NODE_ENV=local`.
Let me know how you get on with this, hopefully this will set you on your way.

**Comment by carlInvoker666** [comment]
![Capture](https://user-images.githubusercontent.com/85369689/120995359-e92e4b80-c7b7-11eb-852b-d45bcb2346c5.JPG)
this is the one im facing right now @13ROY... hope you can help me out with this isssue. Thank you so much

**Comment by 13ROY** [comment]
Hi @carlInvoker666 , this where the app can't find the file you have created with the configuration (e.g `.env.local`).
It is the `NODE_ENV` terminal value that needs to be set to the **same name** as the configuration file, apologies for my previous message, I gave you the unix example to set this value (`export NODE_ENV=local`) , the windows command should be  `set NODE_ENV=local`, does this help?

**Comment by samc621** [comment]
@13ROY is exactly on the money, thanks for the help here!

Closing this for now, feel free to open if any new issues occur.
