### ISSUE TITLE
 Hi, running the 'npx knex migrate: latest' command keeps giving errors. Could you help me please?

### ISSUE THREAD

**Issue by Z1m0** [samc621/SneakerBot#42]
The error displayed in the console is the following:
"Error: knex: Required configuration option 'client' is missing."

**Comment by Z1m0** [comment]
Hello again,
i think i solved by setting the environment variable NODE_ENV with this command:
$env:NODE_ENV = 'local'
Using Powershell

**Comment by samc621** [comment]
Yup that sounds like the correct solution. That error almost always means the NODE_ENV wasn't set. Closing this for now!
