### ISSUE TITLE
Example post request fails (Insert into... violates foreign key constraint)

### ISSUE THREAD

**Issue by delamae** [samc621/SneakerBot#59]
From the docs https://documenter.getpostman.com/view/5027621/TVt2c3ed

I tried
> curl --location -g --request POST 'localhost:8080/v1/tasks' \
--header 'Content-Type: application/json' \
--data-raw '{
    "site_id": 1,
    "url": "https://www.nike.com/t/lebron-18-black-white-basketball-shoe-M6DgN2/CQ9283-100",
    "style_index": 1,
    "size": "8.5",
    "shipping_speed_index": 0,
    "billing_address_id": 2,
    "shipping_address_id": 2,
    "notification_email_address": "jsmith@gmail.com"
}'

response:
>{"success":false,"message":"insert into \"tasks\" (\"billing_address_id\", \"notification_email_address\", \"shipping_address_id\", \"shipping_speed_index\", \"site_id\", \"size\", \"style_index\", \"url\") values ($1, $2, $3, $4, $5, $6, $7, $8) returning * - insert or update on table \"tasks\" violates foreign key constraint \"tasks_billing_address_id_foreign\"","data":{}}

I can do
>curl --location -g --request GET 'localhost:8080/v1/tasks' \
--header 'Content-Type: application/json'

which returns
>{"success":true,"message":"Tasks not found","data":[]}

Nevertheless, I can't get the first POST to work. Using Lubuntu 20.04.

 Thoughts?

**Comment by samc621** [comment]
Hi @delamae,

`billing_address_id` and `shipping_address_id` are foreign keys. Have you created a billing address in your DB with an ID of two? If not, that's an invalid foreign key ID in your payload (that's what this error is suggesting). You need to create an address before you can create a task, because the address ID is used in the payload.

**Comment by delamae** [comment]
Success.
`{"success":true,"message":"Task successfully created","data":{"id":10,"site_id":1,"url":"https://www.nike.com/t/lebron-18-black-white-basketball-shoe-M6DgN2/CQ9283-100","style_index":1,"size":"8.5","shipping_speed_index":0,"billing_address_id":2,"shipping_address_id":2,"notification_email_address":"jsmith@gmail.com","created_at":"2021-11-17T02:44:30.915Z","updated_at":"2021-11-17T02:44:30.915Z","is_deleted":false,"auto_solve_captchas":true,"product_code":null}}
`

I incorrectly assumed that knex seeded these due to my fundamental misunderstanding of the structure. I see why storing values like this is useful: in this way, multiple, varying addresses can be used from the db. That's handy.

Here's an example in pgadmin, in case it's useful for others:
https://ibb.co/jZB0hgN
