### ISSUE TITLE
Feature request: Add promo/coupon code option for Shopify

### ISSUE THREAD

**Issue by delamae** [samc621/SneakerBot#60]
.Closing

**Comment by delamae** [comment]
Oh, I just realized all these fields are probably being populated with POST requests, rather than traversing the DOM. My mistake. Looks like the reduction code can be in postData params as
            ` {
                "name": "checkout%5Breduction_code%5D",
                "value": ""
              }`

**Comment by samc621** [comment]
HI @delamae thanks for opening this issue and also investigating it yourself! If you do go ahead and implement this field, do you mind submitting a Pull Request so we can add it to the codebase? That way everyone can benefit from it. Thanks!

**Comment by delamae** [comment]
Sure thing. I cleared my comment and OP because I was so off base, I didn't want to confuse anyone, hah. I also noticed some sites have unique selectors, but because Playwright's syntax is pretty simple, they're easy to change out, but at the same time not always consistent enough for the codebase.

As far as the pull request, I'll send one if I get it working. I haven't tested this yet, but what I'm looking at right now is
`
    //insert after line 179
    const promoCodeSelector = 'input#checkout_reduction_code_mobile'; //i'm not on mobile but that's the name i'm seeing anyway
    const promoCode = '20j2923i923ri'; //ultimately this value's better either in the .env or the db
    await page.waitForSelector(promoCodeSelector);
    await page.type(promoCodeSelector, promoCode, {
      delay: 10
    });
    await page.waitForTimeout(250);
    await page.click('button:has-text("Apply Discount Code")');
    await page.waitForTimeout(2000);
`

Many parts of this project were new to me and I was getting parts mixed with simultaneous projects, but now that I've got it running to the end, I should have some useful contributions.

**Comment by samc621** [comment]
@delamae nice, feel free to put up the PR and I will test it! Btw, we're on Puppeteer, which is syntactically similar to Playwright, but just wanted to correct that.

**Comment by delamae** [comment]
Ah yes, I'm working simultaneously on a Playwright project. I think the has-text in the above code is a Playwright thing, so I'll find another way if it is.

**Comment by delamae** [comment]
I think this may be puppeteer's syntax to add the promo code, but I haven't tested it:
```
    //in sites/shopify.js, insert after line 179
    const promoCodeSelector = 'input#checkout_reduction_code_mobile';
    const promoCode = '20j2923i923ri'; //ultimately this value's better either in the .env or the db
    await page.waitForSelector(promoCodeSelector);
    await page.type(promoCodeSelector, promoCode, {
      delay: 10
    });
    await page.waitForTimeout(2000);

    const promoCodeSubmitSelector = 'button.field__input-btn.btn'; //least likely part to be correct
    await page.waitForSelector(promoCodeSubmitSelector);
    await page.click(promoCodeSubmitSelector); 
    await page.waitForTimeout(2000);
```
where 'button.field__input-btn.btn' is attempting to be the selector for
```
<button name="button" type="submit" class="field__input-btn btn" aria-busy="false">
  ...
</button>
```

I think a promo code would be the kind of thing better to store in the db or some .json like the CC's rather than the .env, but I haven't studied that part of the repo yet to get an idea of how to best take it from there.
