### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'querySelectorAll')

### ISSUE THREAD

**Issue by james5101** [samc621/SneakerBot#61]
Hi, I am trying to run a task and am receiving the following error. 
![image](https://user-images.githubusercontent.com/16067136/144775877-52fc691b-4801-4ffa-bc42-3620f3b8feee.png)

Not sure if its a code issue or an issue with my payload.

**Comment by samc621** [comment]
@james5101 thanks for the stack trace, can you paste the task payload you're using? I'll try to repo this issue. Seems like the `document` object is null on the window.

**Comment by james5101** [comment]
@samc621 Sure thing, here is the payload for the task creation:
{    
      "site_id": 5,
      "url": "https://www.supremenewyork.com/shop/tops-sweaters/vf80od3z4/kxesnt6v7",
      "style_index": 1,
      "size": "M",
      "shipping_speed_index": 0,
      "billing_address_id": 1,
      "shipping_address_id": 1,
      "notification_email_address": "jamescnoonan@yahoo.com"
    }

I tried a couple different things for "size" including "M", "Medium" and upon further investigation when inspecting the HTML it looks like they assign values to the different sizes. Here's a screenshot
![image](https://user-images.githubusercontent.com/16067136/144871176-3e591041-494e-4e83-a1e9-6d7f1c67e7b4.png)

**Comment by camille-vo** [comment]
Had this problem too - there's a typo on line 228 of supremenewyork.js
`        const form = document.querySelector('div#cctrl form#cart-addf')
`
Changed cart-addf to cart-add and it worked fine

**Comment by samc621** [comment]
@camille-vo nice find! Can you submit a PR to fix this? I will happily review and merge.

**Comment by camille-vo** [comment]
@samc621 Sure! This is my first time contributing to a public repo, so hopefully I did the process correctly
Do you have an idea for a UI? I'd love to build one if you have an idea of the layout you'd want etc.

**Comment by samc621** [comment]
Closing this as it's now resolved.
