### ISSUE TITLE
database tables don't exist

### ISSUE THREAD

**Issue by mbw290** [samc621/SneakerBot#66]
insert into "addresses" ("address_line_1", "city", "country", "email_address", "first_name", "last_name", "phone_number", "postal_code", "state", "type") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning * - relation "addresses" does not exist

**Comment by samc621** [comment]
@mbw290 did you run the migrations? See [here](https://github.com/samc621/SneakerBot#run-the-db-migrations). 

`knex migrate:latest`

Please follow each of the setup instructions in the README.

**Comment by samc621** [comment]
Closing this, feel free to reopen if any issues persist.

**Comment by ChrisxDumas** [comment]
@samc621 just to be clear, we just create the database without the actual tables and the migration will take care of that?

**Comment by samc621** [comment]
@ChrisxDumas that's correct. Create the database and then run the migrations and seeders.
