### ISSUE TITLE
Having issues running npx knex migrate:latest + Password 

### ISSUE THREAD

**Issue by SLEsserman** [samc621/SneakerBot#70]
<img width="568" alt="Screen Shot 2022-03-22 at 4 32 52 PM" src="https://user-images.githubusercontent.com/59885495/159570827-ce51138c-58ce-4adf-955f-1ceee973cab5.png">
<img width="308" alt="Screen Shot 2022-03-22 at 4 33 47 PM" src="https://user-images.githubusercontent.com/59885495/159570957-b8e0766a-59d4-4b8b-ac53-f0255f8273a6.png">

**Comment by samc621** [comment]
@SLEsserman I haven't seen this before. I assume you made a new file like `.env.local` or `.env.development`, where you're keeping those vars, right? Did you specify the proper `NODE_ENV` name in the terminal? E.g. `export NODE_ENV=local` ? If so, I would try a debug statement like `console.log(process.env.DB_PASSWORD)` in `knexfile.js` to see if the variable is being read properly.

**Comment by samc621** [comment]
Hi @SLEsserman I hope that you've been able to sort this by now. Closing it, but feel free to open a new one if the issues persist.
