### ISSUE TITLE
'knex migrate: latest' issue

### ISSUE THREAD

**Issue by bpnis** [samc621/SneakerBot#78]
I am having a problem with running the knex migrate: latest command on windows, similar to other people. I've tried running the following command in powershell (which i found in a solved issue) , but it hasn't worked for me. Any ideas?

![powershell](https://user-images.githubusercontent.com/106709611/171511125-96d2b022-711e-4ca0-b440-63c7550455e1.PNG)

Thanks in advance.

**Comment by samc621** [comment]
@bpnis can you try `$ set NODE_ENV=local` ? See https://github.com/samc621/SneakerBot#windows

**Comment by bpnis** [comment]
I just tried it, and this is what I got:

![2022-06-02](https://user-images.githubusercontent.com/106709611/171727447-315d80c3-4061-4472-beb6-20e375d4f1a2.png)

Thank you so much for the help by the way, I really appreciate it!

**Comment by samc621** [comment]
@bpnis sorry for the confusion, the "$" in all of the commands is not meant to be typed. It's just supposed to indicate that it's something you enter in the shell/terminal. So just enter `set NODE_ENV=local`.

**Comment by bpnis** [comment]
Yep that worked lol. Thank you so much, I'm new to Javascript so i guess its a rookie mistake. I'll go ahead and close the issue.
