### ISSUE TITLE
Help - configuration

### ISSUE THREAD

**Issue by soermejo** [samc621/SneakerBot#8]
Do we need to create a db before and then set .env variables?
what is PORT=.. ? referred to and is it mandatory to set?

Also only knex is not working. I'm using "npx knex ..command" (i never used it, don't know if that's right)

I also wonder... wouldn't it be better and faster to use only pure requests instead of running multiple instances of puppeter which is way more cpu consuming and slower.

**Comment by bryank91** [comment]
not the developer but PORT refers to where the API will be hosted on.
so if you use PORT=6000, you can hit the api at localhost:6000 

you will need to install knex globally
https://gist.github.com/NigelEarle/80150ff1c50031e59b872baf0e474977

**Comment by samc621** [comment]
Hi @soermejo, yes @bryank91 is correct - `PORT` in the env variables is the port the Node server will run on. So if you set `PORT=6000`, you will send API requests to `localhost:6000`. 

As for `knex`, I do not think you need to install it globally. It's in the `package.json` so when you run `npm i` or `npm install`, it should be installed. Please refer [here](https://knexjs.org/) for a basic guide on using `knex`.

I am closing this for now, but feel free to reopen if you have any further issues.
