### ISSUE TITLE
Having issue running npx knex migrate:latest

### ISSUE THREAD

**Issue by NikhilRN18** [samc621/SneakerBot#82]
I keep getting the error: knex: Required configuration option 'client' is missing.
I have tried the previous solution of set NODE_ENV=local in PowerShell, however that hasn't helped either.
![knexerror](https://user-images.githubusercontent.com/107941991/184410205-91bb1d7e-5c3c-4e7d-b41f-26aaa326db74.png)

**Comment by Jayjdd2** [comment]
Having the same issue as above. Tried previous solution and none working

**Comment by samc621** [comment]
@Jayjdd2 thanks for the comment. Yes, on Windows you need to use SETX, as documented in the README. 

I'm closing this now, but feel free to open a new Issue if any problems persist.
