### ISSUE TITLE
Issue:  sql: select * from "proxies" where "is_deleted" = ? 

### ISSUE THREAD

**Issue by Dropio12** [samc621/SneakerBot#83]
What am I supposed to write after this?  It doesnt let me put any characters in the terminal after this. Thanks for the help!
![eror](https://user-images.githubusercontent.com/93799788/185487464-a24d94f8-6a60-4068-9bcb-cd3e0101243e.PNG)

**Comment by samc621** [comment]
@Dropio12 that is not an error log, it's just a debug statement from PG. You have the server running now, so you can use the API to create addresses and tasks. I suggest following the instructions in the README. I am going to close this Issue, please feel free to open a new one if any issues persist.
