### ISSUE TITLE
getaddrinfo ENOTFOUND 127.0.0.1',

### ISSUE THREAD

**Issue by ChrisxDumas** [samc621/SneakerBot#90]
so when I do `npm start`
I get the following message, I am not sure how to go from there to configure the website or item I want to buy

```
$ npm start

> sneakerbot@1.0.0 start
> node ./app.js

App listening at port 8080
{
  method: 'raw',
  sql: 'select 1+1 as result',
  bindings: [],
  options: {},
  __knexQueryUid: 'SzJD0WMW0eWdX4-Q54uR-'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ false, false ],
  __knexQueryUid: '0RfGAZ4MaQEYt0ng4zKvv',
  sql: 'select * from "proxies" where "is_deleted" = ? and "has_been_used" = ? order by "created_at" desc'
}
```

I am not sure what to expect when this runs. how do I know it's working? does it open a webpage?  is it gonna print something?

when I go to http://localhost:8080/ I get `Cannot GET /`

**Comment by samc621** [comment]
@ChrisxDumas please follow the usage instructions in the README. This is not a web application, it's a Node server application which exposes an Express.js RESTful API. You can interact with the API to configure addresses/tasks and then run the tasks. This happens 100% on the server side and will not launch a browser unless you leave Puppeteer in the `headless: false` mode.
