### ISSUE TITLE
Update knex-mock-client version

### ISSUE THREAD

**Issue by Ranzeb** [samc621/SneakerBot#94]
While trying to npm install from package.json, it seems that knex 2.3.0 dependencies and knex-mock-client version 1.6.2 under devDependencies are in conflict.

Try to update the knex-mock-client to 1.7.0 version

**Comment by Ranzeb** [comment]
And now having this problem when trying to execute npx knew migrate:latest

knex: Required configuration option 'client' is missing.
Error: knex: Required configuration option 'client' is missing.
    at new Client (C:\Users\rranz\Desktop\NikeBot\SneakerBot\node_modules\knex\lib\client.js:58:13)
    at knex (C:\Users\rranz\Desktop\NikeBot\SneakerBot\node_modules\knex\lib\knex-builder\Knex.js:16:28)
    at initKnex (C:\Users\rranz\Desktop\NikeBot\SneakerBot\node_modules\knex\bin\cli.js:84:10)
    at async Command.<anonymous> (C:\Users\rranz\Desktop\NikeBot\SneakerBot\node_modules\knex\bin\cli.js:247:26)
    
    
How can I solve that?

**Comment by samc621** [comment]
> While trying to npm install from package.json, it seems that knex 2.3.0 dependencies and knex-mock-client version 1.6.2 under devDependencies are in conflict.
> 
> Try to update the knex-mock-client to 1.7.0 version

@Ranzeb did you try making this upgrade and testing it? If it works, you can open a PR and I'll happily test it from my end before merging.

**Comment by samc621** [comment]
> And now having this problem when trying to execute npx knew migrate:latest
> 
> knex: Required configuration option 'client' is missing. Error: knex: Required configuration option 'client' is missing. at new Client (C:\Users\rranz\Desktop\NikeBot\SneakerBot\node_modules\knex\lib\client.js:58:13) at knex (C:\Users\rranz\Desktop\NikeBot\SneakerBot\node_modules\knex\lib\knex-builder\Knex.js:16:28) at initKnex (C:\Users\rranz\Desktop\NikeBot\SneakerBot\node_modules\knex\bin\cli.js:84:10) at async Command. (C:\Users\rranz\Desktop\NikeBot\SneakerBot\node_modules\knex\bin\cli.js:247:26)
> 
> How can I solve that?

Make sure you specify the `NODE_ENV` in your env. It should match the name of your `.env` file e.g. if you use `.env.local` then set your `NODE_ENV=local`.

Closing this issue, please feel free to open a new one if any issues persist.

**Comment by Ranzeb** [comment]
The change in the package.json seems to work on my side but before I want to fully run the application.

I've followed your step-by-step installation but I still have that annoying problem. 

I've tried both to call the env file like ".env", ".env.local", ".env.devolpment" and set NODE_ENV= to the name of the file but it's not working on my side.

Just for info, I'm on windows with node 16.15.1

**Comment by Ranzeb** [comment]
`import { config } from 'dotenv-flow';

config();

const local = {
  client: 'pg',
  connection: {
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    user: process.env.DB_USERNAME,
    database: process.env.DB_NAME,
    password: process.env.DB_PASSWORD
  },
  useNullAsDefault: true,
  debug: true,
  migrations: {
    directory: 'db/migrations',
    tableName: 'knex_migrations'
  },
  seeds: {
    directory: 'db/seeds'
  }
};

const docker = {
  ...local,
  debug: false
};

export default {
  local,
  test: local,
  docker
};
`

This is my knexfile

**Comment by samc621** [comment]
@Ranzeb did you try using `SETX` ?

**Comment by Ranzeb** [comment]
@samc621 setx does not work.

![image](https://user-images.githubusercontent.com/104820500/214705914-d1163751-699c-4e0a-89df-e258c08a80bd.png)

Am I right to have this variable in my user environment variables on Windows?

**Comment by samc621** [comment]
@Ranzeb yes that is correct. I recommend using SETX from your terminal. e.g. `setx NODE_ENV local`. Then you can use echo to print the value and confirm that it is set properly e.g. `echo %NODE_ENV%.
